apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "plugins.nri-plugins.io/v1alpha1",
          "kind": "BalloonsPluginConfig",
          "metadata": {
            "name": "balloonspluginconfig-sample"
          },
          "spec": {
            "config": {
              "policy": {
                "ReservedResources": {
                  "cpu": "750m"
                }
              }
            },
            "hostPort": 8891,
            "image": {
              "name": "ghcr.io/containers/nri-plugins/nri-resource-policy-balloons",
              "pullPolicy": "IfNotPresent"
            },
            "initContainerImage": {
              "name": "ghcr.io/containers/nri-plugins/nri-config-manager",
              "pullPolicy": "IfNotPresent"
            },
            "nri": {
              "patchRuntimeConfig": false
            },
            "resources": {
              "cpu": "500m",
              "memory": "512Mi"
            },
            "tolerations": []
          }
        },
        {
          "apiVersion": "plugins.nri-plugins.io/v1alpha1",
          "kind": "MemoryQosPluginConfig",
          "metadata": {
            "name": "memoryqospluginconfig-sample"
          },
          "spec": {
            "image": {
              "name": "ghcr.io/containers/nri-plugins/nri-memory-qos",
              "pullPolicy": "IfNotPresent"
            },
            "initContainerImage": {
              "name": "ghcr.io/containers/nri-plugins/nri-config-manager",
              "pullPolicy": "IfNotPresent"
            },
            "nri": {
              "patchRuntimeConfig": false
            },
            "resources": {
              "cpu": "10m",
              "memory": "100Mi"
            },
            "tolerations": []
          }
        },
        {
          "apiVersion": "plugins.nri-plugins.io/v1alpha1",
          "kind": "MemtierdPluginConfig",
          "metadata": {
            "name": "memtierdpluginconfig-sample"
          },
          "spec": {
            "image": {
              "name": "ghcr.io/containers/nri-plugins/nri-memtierd",
              "pullPolicy": "IfNotPresent"
            },
            "initContainerImage": {
              "name": "ghcr.io/containers/nri-plugins/nri-config-manager",
              "pullPolicy": "IfNotPresent"
            },
            "nri": {
              "patchRuntimeConfig": false
            },
            "outputDir": "",
            "resources": {
              "cpu": "250m",
              "memory": "100Mi"
            },
            "tolerations": []
          }
        },
        {
          "apiVersion": "plugins.nri-plugins.io/v1alpha1",
          "kind": "TopologyAwarePluginConfig",
          "metadata": {
            "name": "topologyawarepluginconfig-sample"
          },
          "spec": {
            "config": {
              "policy": {
                "ReservedResources": {
                  "cpu": "750m"
                }
              }
            },
            "hostPort": 8891,
            "image": {
              "name": "ghcr.io/containers/nri-plugins/nri-resource-policy-topology-aware",
              "pullPolicy": "IfNotPresent"
            },
            "initContainerImage": {
              "name": "ghcr.io/containers/nri-plugins/nri-config-manager",
              "pullPolicy": "IfNotPresent"
            },
            "nri": {
              "patchRuntimeConfig": false
            },
            "resources": {
              "cpu": "500m",
              "memory": "512Mi"
            },
            "tolerations": []
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-11-03T12:33:07Z"
    operators.operatorframework.io/builder: operator-sdk-v1.32.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: nri-plugins-unified-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: BalloonsPluginConfig
      name: balloonspluginconfigs.plugins.nri-plugins.io
      version: v1alpha1
    - kind: MemoryQosPluginConfig
      name: memoryqospluginconfigs.plugins.nri-plugins.io
      version: v1alpha1
    - kind: MemtierdPluginConfig
      name: memtierdpluginconfigs.plugins.nri-plugins.io
      version: v1alpha1
    - kind: TopologyAwarePluginConfig
      name: topologyawarepluginconfigs.plugins.nri-plugins.io
      version: v1alpha1
  description: nri-plugins-operator
  displayName: nri-plugins-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - plugins.nri-plugins.io
          resources:
          - topologyawarepluginconfigs
          - topologyawarepluginconfigs/status
          - topologyawarepluginconfigs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - plugins.nri-plugins.io
          resources:
          - balloonspluginconfigs
          - balloonspluginconfigs/status
          - balloonspluginconfigs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - plugins.nri-plugins.io
          resources:
          - memoryqospluginconfigs
          - memoryqospluginconfigs/status
          - memoryqospluginconfigs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - plugins.nri-plugins.io
          resources:
          - memtierdpluginconfigs
          - memtierdpluginconfigs/status
          - memtierdpluginconfigs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: nri-plugins-unified-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: nri-plugins-unified-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: nri-plugins-unified-operator
          control-plane: controller-manager
        name: nri-plugins-unified-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=nri-plugins-unified-operator
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: nri-plugins-unified-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: nri-plugins-unified-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nri
  - resource-management
  - cri-o
  - containerd
  - kubernetes
  links:
  - name: Nri Plugins Unified Operator
    url: https://nri-plugins-unified-operator.domain
  maintainers:
  - email: feruzjon.muyassarov@intel.com
    name: fmuyassarov
  maturity: alpha
  provider:
    name: containers/nri-plugins github project owners
    url: https://github.com/containers/nri-plugins
  version: 0.0.1
