apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for plugins.nri-plugins.io/v1alpha1, Kind: TopologyAwarePluginConfig
##
- apiGroups:
  - plugins.nri-plugins.io
  resources:
  - topologyawarepluginconfigs
  - topologyawarepluginconfigs/status
  - topologyawarepluginconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"

##
## Rules for plugins.nri-plugins.io/v1alpha1, Kind: BalloonsPluginConfig
##
- apiGroups:
  - plugins.nri-plugins.io
  resources:
  - balloonspluginconfigs
  - balloonspluginconfigs/status
  - balloonspluginconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"

##
## Rules for plugins.nri-plugins.io/v1alpha1, Kind: MemoryQosPluginConfig
##
- apiGroups:
  - plugins.nri-plugins.io
  resources:
  - memoryqospluginconfigs
  - memoryqospluginconfigs/status
  - memoryqospluginconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"

##
## Rules for plugins.nri-plugins.io/v1alpha1, Kind: MemtierdPluginConfig
##
- apiGroups:
  - plugins.nri-plugins.io
  resources:
  - memtierdpluginconfigs
  - memtierdpluginconfigs/status
  - memtierdpluginconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"

#+kubebuilder:scaffold:rules
