name: Chart Lint
on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow
    
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Lint Helm charts
        uses: helm/chart-testing-action@v2.4.0
        run: ct lint --config ct.yaml
