name: Submit release OLM bundle

# on:
#   release:
#     types:
#       - published
on:
  push:
    tags:
      - v0.**

jobs:
  createPullRequest:
    name: Publish new OperatorHub release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the bundle
        run: pushd deployment/operator && make bundle && popd

      - name: Checkout upstream community-operators repo
        uses: actions/checkout@v4
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators
          ref: main
          token: ${{ secrets.BOT_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: community-operators

      - name: Copy the bundle to the community-operators repo
        run: |
          mkdir -p community-operators/operators/nri-plugins-operator/${{ github.ref_name }}
          cp -r deployment/operator/bundle/ community-operators/operators/nri-plugins-operator/${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          signoff: true
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          draft: true
          add-paths: |
            operators/nri-plugins-operator/**
          committer: "Github Actions <${{ steps.import-gpg.outputs.email }}>"
          path: community-operators
          push-to-fork: nri-plugins-bot/community-operators
          branch: olm-${{ github.ref_name }}
          token: ${{ secrets.BOT_PAT }}
          delete-branch: false
          title: 'nri-plugins-operator ${{ github.ref_name }}'
          commit-message: 'Submit operator nri-plugins-operator ${{ github.ref_name }}'
          body: |
            Added OLM bundle for [nri-plugins operator ${{ github.ref_name }}](https://github.com/containers/nri-plugins/releases/tag/${{ github.ref_name }})
            > Auto-generated by `Github Actions Bot`
