name: Publish a release

on:
  push:
    tags:
      - '*' # Triggers on any tag creation

jobs:
  update:
    name: Publish new OperatorHub release
    runs-on: ubuntu-latest
    steps:
      # - name: pwd
      #   run: cd && pwd

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: fmuyassarov/operator-demo
          path: __operator-demo
          ref: main
          token: ${{ secrets.MACHINE_PAT }}
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.MACHINE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MACHINE_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: __operator-demo

      - name: Make changes
        run: date +%s >__operator-demo/report.txt

      # - name: move
      #   run: cd operator-demo && pwd
        # working-directory: operator-demo

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MACHINE_PAT }}
          push-to-fork: nri-plugins-bot/operator-demo
          commit-message: nri-plugins-operator
          branch: example-patches
          signoff: false
          committer: "Github Actions foo@example.com"
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: 'nri-plugins-operator: XYZ'
          body: |
            Added OLM package for [nri-plugins Operator: Auto-generated by `Github Actions Bot`
