name: Publish a release

on:
  push:
    tags:
      - '*' # Triggers on any tag creation

jobs:
  update:
    name: Publish new OperatorHub release
    runs-on: ubuntu-latest
    steps:
      - name: Check out OperatorHub operators repo fork
        uses: actions/checkout@v4
        with:
          repository: nri-plugins-bot/operator-demo
          ref: main
          token: ${{ secrets.MACHINE_PAT }}
          path: operator-demo

      - name: Make changes
        run: date +%s > report.txt
        working-directory: operator-demo

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MACHINE_PAT }}
          push-to-fork: 'nri-plugins-bot/operator-demo'
          commit-message: 'nri-plugins-operator: XYZ'
          branch: example-patches
          signoff: false
          committer: "Github Actions foo@example.com"
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: 'nri-plugins-operator: XYZ'
          body: |
            Added OLM package for [nri-plugins Operator: Auto-generated by `Github Actions Bot`
