name: Publish a release

on:
  push:
    tags:
      - '*' # Triggers on any tag creation

jobs:
  update:
    name: Publish new OperatorHub release
    runs-on: ubuntu-22.04
    steps:

      - name: Get the release tag
        run: echo ${GITHUB_REF##*/}

      - name: Get the release tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run make bundle
        run: pushd deployment/operator && ls -lah && pwd && popd

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: fmuyassarov/operator-demo
          path: operator-demo
          ref: main
          token: ${{ secrets.MACHINE_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.MACHINE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MACHINE_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: operator-demo

      - name: Make changes to pull request
        run: date +%s > operator-demo/report.txt

      - name: Run pwd
        run: cp nri-plugins/Makefile operator-demo/foo && ls -lah operator-demo/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          signoff: true
          committer: "Github Actions <${{ steps.import-gpg.outputs.email }}>"
          path: operator-demo
          push-to-fork: nri-plugins-bot/operator-demo
          branch: olm-${{ github.ref_name }}
          token: ${{ secrets.MACHINE_PAT }}
          delete-branch: false
          title: 'operator nri-plugins-operator ${{ github.ref_name }}'
          commit-message: 'Submit operator nri-plugins-operator ${{ github.ref_name }}'
          body: |
            Added OLM bundle for [nri-plugins operator ${{ github.ref_name }}](https://github.com/containers/nri-plugins/releases/tag/${{ github.ref_name }})
            > Auto-generated by `Github Actions Bot`